
import { Product, Category } from './types';

export const CATEGORIES: Category[] = ['All', 'Indoor', 'Outdoor', 'Bouquets', 'Succulents', 'Gifts'];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Monstera Deliciosa',
    category: 'Indoor',
    price: 45.00,
    image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&q=80&w=800',
    description: 'The iconic Swiss Cheese Plant. Famous for its natural leaf holes, it adds a tropical feel to any room.',
    careLevel: 'Easy',
    sunlight: 'Moderate',
    water: 'Weekly',
    rating: 4.8,
    reviews: 124,
    isBestseller: true,
  },
  {
    id: '2',
    name: 'Snake Plant Laurentii',
    category: 'Indoor',
    price: 32.00,
    image: 'https://images.unsplash.com/photo-1593482892290-f54927ae1bf6?auto=format&fit=crop&q=80&w=800',
    description: 'An architectural wonder that is nearly impossible to kill. Perfect for air purification.',
    careLevel: 'Easy',
    sunlight: 'Low',
    water: 'Bi-weekly',
    rating: 4.9,
    reviews: 89,
    isBestseller: true,
  },
  {
    id: '3',
    name: 'Wild Orchid Bouquet',
    category: 'Bouquets',
    price: 75.00,
    image: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&q=80&w=800',
    description: 'Elegant white and purple orchids curated for special moments. Includes a ceramic vase.',
    careLevel: 'Easy',
    sunlight: 'Moderate',
    water: 'Daily',
    rating: 4.7,
    reviews: 45,
  },
  {
    id: '4',
    name: 'Desert Gem Succulent Mix',
    category: 'Succulents',
    price: 28.00,
    image: 'https://images.unsplash.com/photo-1520302630591-fd1c66ed11ef?auto=format&fit=crop&q=80&w=800',
    description: 'A beautiful arrangement of 5 mini succulents in a concrete planter.',
    careLevel: 'Easy',
    sunlight: 'Full Sun',
    water: 'Bi-weekly',
    rating: 4.6,
    reviews: 56,
  },
  {
    id: '5',
    name: 'English Garden Rose',
    category: 'Outdoor',
    price: 55.00,
    image: 'https://images.unsplash.com/photo-1496062031456-07b8f162a322?auto=format&fit=crop&q=80&w=800',
    description: 'Classic fragrant roses that bloom all summer long. Perfect for patios.',
    careLevel: 'Intermediate',
    sunlight: 'Full Sun',
    water: 'Daily',
    rating: 4.9,
    reviews: 32,
  },
  {
    id: '6',
    name: 'Peace Lily',
    category: 'Indoor',
    price: 38.00,
    image: 'https://images.unsplash.com/photo-1597055181300-e3633a107f18?auto=format&fit=crop&q=80&w=800',
    description: 'Symbolizing tranquility and purity, the Peace Lily is a great indoor air cleaner.',
    careLevel: 'Intermediate',
    sunlight: 'Low',
    water: 'Weekly',
    rating: 4.5,
    reviews: 110,
  },
  {
    id: '7',
    name: 'Fiddle Leaf Fig',
    category: 'Indoor',
    price: 120.00,
    image: 'https://images.unsplash.com/photo-1597055181300-e3633a107f18?auto=format&fit=crop&q=80&w=800',
    description: 'The designer\'s favorite. Large, waxy leaves that create a bold statement.',
    careLevel: 'Advanced',
    sunlight: 'Moderate',
    water: 'Weekly',
    rating: 4.4,
    reviews: 210,
    isBestseller: true,
  },
  {
    id: '8',
    name: 'Lavender Fields',
    category: 'Outdoor',
    price: 24.00,
    image: 'https://images.unsplash.com/photo-1471943311424-646960669fbc?auto=format&fit=crop&q=80&w=800',
    description: 'Fragrant and calming. Great for attracting pollinators to your balcony.',
    careLevel: 'Easy',
    sunlight: 'Full Sun',
    water: 'Bi-weekly',
    rating: 4.8,
    reviews: 78,
  },
  {
    id: '9',
    name: 'Birthday Bloom Gift Box',
    category: 'Gifts',
    price: 85.00,
    image: 'https://images.unsplash.com/photo-1522673607200-164883eecd0c?auto=format&fit=crop&q=80&w=800',
    description: 'A curated gift box with a mini plant, organic candle, and gourmet chocolate.',
    careLevel: 'Easy',
    sunlight: 'Moderate',
    water: 'Weekly',
    rating: 5.0,
    reviews: 15,
  },
  {
    id: '10',
    name: 'Zamioculcas Zamiifolia (ZZ)',
    category: 'Indoor',
    price: 40.00,
    image: 'https://images.unsplash.com/photo-1632207691143-643e2a9a9361?auto=format&fit=crop&q=80&w=800',
    description: 'The ultimate low-light survivor with shiny, emerald green leaves.',
    careLevel: 'Easy',
    sunlight: 'Low',
    water: 'Bi-weekly',
    rating: 4.9,
    reviews: 95,
  },
  {
    id: '11',
    name: 'Golden Pothos',
    category: 'Indoor',
    price: 22.00,
    image: 'https://images.unsplash.com/photo-1612363148167-2694881554dd?auto=format&fit=crop&q=80&w=800',
    description: 'A trailing plant that grows quickly and is extremely resilient.',
    careLevel: 'Easy',
    sunlight: 'Moderate',
    water: 'Weekly',
    rating: 4.7,
    reviews: 200,
  },
  {
    id: '12',
    name: 'String of Pearls',
    category: 'Succulents',
    price: 35.00,
    image: 'https://images.unsplash.com/photo-1614594805320-e6a5549d7f95?auto=format&fit=crop&q=80&w=800',
    description: 'Unique succulent with cascading green beads. A stunning hanging plant.',
    careLevel: 'Intermediate',
    sunlight: 'Moderate',
    water: 'Bi-weekly',
    rating: 4.6,
    reviews: 42,
  },
  {
    id: '13',
    name: 'Echeveria Rosetta',
    category: 'Succulents',
    price: 15.00,
    image: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?auto=format&fit=crop&q=80&w=800',
    description: 'Classic rosette-shaped succulent with soft grey-blue foliage.',
    careLevel: 'Easy',
    sunlight: 'Full Sun',
    water: 'Bi-weekly',
    rating: 4.8,
    reviews: 67,
  },
  {
    id: '14',
    name: 'Red Passion Bouquet',
    category: 'Bouquets',
    price: 65.00,
    image: 'https://images.unsplash.com/photo-1591880911456-586b8c9f21df?auto=format&fit=crop&q=80&w=800',
    description: 'Deep red roses mixed with seasonal fillers. For the one you love.',
    careLevel: 'Easy',
    sunlight: 'Low',
    water: 'Daily',
    rating: 4.9,
    reviews: 130,
    isBestseller: true,
  },
  {
    id: '15',
    name: 'Bonsai Ficus Microcarpa',
    category: 'Gifts',
    price: 95.00,
    image: 'https://images.unsplash.com/photo-1512428813834-c702c7702b78?auto=format&fit=crop&q=80&w=800',
    description: 'An ancient art form in a pot. A symbol of harmony and balance.',
    careLevel: 'Advanced',
    sunlight: 'Moderate',
    water: 'Daily',
    rating: 4.5,
    reviews: 28,
  }
];
